# shellcheck shell=bash

format:
   #!/usr/bin/env bash
   fourmolu -i src app test
   cabal-fmt -i anti.cabal

hlint:
  #!/usr/bin/env bash
  hlint app src test

test:
  #!/usr/bin/env bash
  cabal test

build:
    #!/usr/bin/env bash
    cabal build all

CI:
  #!/usr/bin/env bash
  set -euo pipefail
  just build
  just test
  cabal-fmt -c anti.cabal
  fourmolu -m check src app test
  hlint -c src app test
